# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 09:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IOU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='date',
            new_name='dateCreated',
        ),
        migrations.AddField(
            model_name='participant',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='transaction',
            name='dateModified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='iou',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.Participant'),
        ),
        migrations.AddField(
            model_name='iou',
            name='sploodl',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.Sploodl'),
        ),
        migrations.AddField(
            model_name='iou',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.Transaction'),
        ),
    ]
