# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 14:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_auto_20160823_0946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='balance',
        ),
    ]
